### ISSUE TITLE
Version Tagging?

### ISSUE THREAD

**Issue by topherfangio** [RodneyEbanks/requirejs-plugin-bower#3]
I realize I'm jumping in and asking a lot! I appreciate the work that you're doing on this!

Is there any way that we could create git tags for each release? It helps when installing as Bower uses the tags to let us select a particular version.

I tried to fork the repo and create the tags (which works fine), but I can't seem to do a pull request that includes them, so I've just copy/pasted my commands below if you're interested:

``` bash
git tag -a 0.0.5 2b7b6c8ecd27db381c9c3f9a3ddd9d40ef9b1738 -m "Version 0.0.5"
git tag -a 0.0.4 af90ecf6f987252e0fcb9a96ba7a2f9d20de7d7b -m "Version 0.0.4"
git tag -a 0.0.3 b0a45bab5bdbb74a622c977829b643011a65a274 -m "Version 0.0.3"
git tag -a 0.0.2 b0a45bab5bdbb74a622c977829b643011a65a274 -m "Version 0.0.2"
git tag -a 0.0.1 2ddf9dd36f6a1ba156f600b75c5bf8f65ce26211 -m "Version 0.0.1"
git push --tags
```

I believe all of the commit hashes correctly correspond to the version listed. Obviously feel free to rename the versions in the quotes at the end; I just did something generic.

Thanks again!

**Comment by RodneyEbanks** [comment]
I feel as the plugin is currently in development I would rather not add tagging, as soon as I issue a release I will add tagging for everything (and another build system to manage it).  

But to resolve the issue you are having if you change your bower.json file to reference the master branch i.e. "requirejs-plugin-bower": "master" or use bower install requirejs-plugin-bower#master --save.  Bower update will always get the last commit.

And as you determined you can do a git clone to you local directory (with pulls), but the branch reference above saves you some work as bower update then works on all your bower components at once.

**Comment by topherfangio** [comment]
I can totally understand that. I actually wanted to revert to the old 0.0.2 version as it was working and I wanted to push it to the other developers on the team.

I wound up just pointing the bower.json to the specific commit, so it was not too difficult.

Thanks for the feedback!
